/* Données des bonnes adresses — Paros, Antiparos et étapes du voyage.
 *
 * Les notes sont attribuées à chaque contributeur (Liste 1 à Liste 5)
 * pour préserver les points de vue et leur intention :
 *   Liste 1 = "Top restos / Restos locaux / Antiparos"  (⭐ coups de cœur)
 *   Liste 2 = "Paros 🇬🇷"                                (bullets, plages + restos)
 *   Liste 3 = "Plages 🏝 / Restaurants 👩🏻‍🍳"             (⛔ à réserver)
 *   Liste 4 = "Google Map – fiches détaillées"            (phones + maps)
 *   Liste 5 = "PLAGES ANTIPAROS / RESTO"                  (Antiparos focus)
 *   Programme = Programme de voyage Grèce (Athènes, Sifnos, Milos, Kimolos)
 *
 * highlight: true  → marqueur ROUGE (★ coup de cœur ou ⛔ réservation prioritaire)
 * reservation: true → tag "à réserver"
 * avoid: true → tag "à éviter" (lieu déconseillé)
 *
 * Sources géocodage / Insta / sites : recherche web (mai 2026).
 * Certaines coordonnées sont approximatives au niveau du village (±100m).
 */
window.PLACES = [

  /* ============================== PAROS — RESTOS ============================== */
  {
    id: "buonvento",
    name: "BuonVento",
    area: "Mesada · Marpissa",
    island: "Paros",
    category: "restaurant",
    cuisine: "Italien néo-napolitain",
    highlight: true,
    reservation: true,
    coords: [37.0563, 25.2570],
    notes: [
      { author: "Liste 1", text: "Top restos ⭐ — meilleures pâtes au bar." },
      { author: "Liste 4", text: "Restaurant italien néo-napolitain avec vue sur la baie, mozzarella maison et cuisine soignée." },
      { author: "Liste 5", text: "Buenvuento ⛔ (soir)." },
    ],
    phone: "+30 22840 42694",
    instagram: "buonventoparos",
    instagram_url: "https://www.instagram.com/buonventoparos/",
    website: "http://www.buonventoristoranteitaliano.it/",
    google_maps_url: "https://maps.app.goo.gl/tNxpsBYDvgbAYSSV8",
    rating: 4.6,
    review_count: 373,
    photo_url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&h=400&fit=crop",
  },
  {
    id: "blue-oyster",
    name: "Blue Oyster",
    area: "Ambelas",
    island: "Paros",
    category: "restaurant",
    cuisine: "Poisson, oursin, vue mer",
    coords: [37.1197, 25.2713],
    notes: [
      { author: "Liste 1", text: "Dans les tops restos." },
      { author: "Liste 2", text: "Dans les meilleures plages/tavernes (Blue Oyster, Ministiri, Taverne Laris)." },
    ],
    phone: "+30 22840 52707",
    instagram: "blueoyster.paros",
    instagram_url: "https://www.instagram.com/blueoyster.paros/",
    website: "https://www.blueoysterparos.com/",
    rating: 4.4,
    review_count: 210,
  },
  {
    id: "cliff",
    name: "The Cliff",
    area: "Plage Lolantonis",
    island: "Paros",
    category: "restaurant",
    cuisine: "Grec-israélien · beach club",
    highlight: true,
    reservation: true,
    coords: [37.0359, 25.2447],
    notes: [
      { author: "Liste 1", text: "Top restos, plage israélienne." },
      { author: "Liste 3", text: "Cliff ⛔ — incontournable." },
      { author: "Liste 5", text: "Plage Paros ambiance israélienne, resto grec israélien exceptionnel." },
    ],
    instagram: "thecliff_lolantonis",
    instagram_url: "https://www.instagram.com/thecliff_lolantonis/",
    website: "https://www.thecliffparos.com/",
    phone: "+30 694 557 9448",
    rating: 3.7,
    review_count: 302,
  },
  {
    id: "arodo",
    name: "Arodo",
    area: "Krios · Parikia",
    island: "Paros",
    category: "restaurant",
    cuisine: "Plage, méditerranéen + sushi",
    highlight: true,
    reservation: true,
    coords: [37.1008, 25.1429],
    notes: [
      { author: "Liste 1", text: "⭐ Resto incroyable et plage de folie." },
      { author: "Liste 3", text: "Arodo ⛔ — réserver resto + transats." },
      { author: "Liste 4", text: "Taverne de plage simple et charmante, excellente pour déjeuner ou dîner en bord de mer." },
      { author: "Liste 5", text: "Plage + resto sublime et excellent." },
    ],
    instagram: "arodo.paros",
    instagram_url: "https://www.instagram.com/arodo.paros/",
    phone: "+30 2284 021308",
    google_maps_url: "https://maps.app.goo.gl/zJokcX4uVFBB8ddD8",
    rating: 4.3,
    review_count: 337,
  },
  {
    id: "il-napolitano",
    name: "Il Napoletano (Eat Napoli)",
    area: "Front de mer · Parikia",
    island: "Paros",
    category: "restaurant",
    cuisine: "Pizza napolitaine au feu de bois",
    coords: [37.0843, 25.1501],
    notes: [
      { author: "Liste 1", text: "Resto du soir — pizza napolitaine ouf." },
      { author: "Liste 3", text: "Il Napolitano — meilleur italien." },
    ],
    instagram: "ilnapoletanoeat",
    instagram_url: "https://www.instagram.com/ilnapoletanoeat/",
    phone: "+30 694 520 9075",
    rating: 4.3,
    review_count: 160,
  },
  {
    id: "siparos",
    name: "Siparos Seaside Restaurant",
    area: "Xifara · Santa Maria",
    island: "Paros",
    category: "restaurant",
    cuisine: "Méditerranéen, vue sur la mer",
    reservation: true,
    coords: [37.1316, 25.2620],
    notes: [
      { author: "Liste 1", text: "Connu, beaucoup de Français mais très bon." },
      { author: "Liste 2", text: "Très bon resto, à réserver." },
      { author: "Liste 3", text: "Siparos." },
    ],
    instagram: "siparos_seaside_restaurant",
    instagram_url: "https://www.instagram.com/siparos_seaside_restaurant/",
    website: "https://siparos.gr/",
    phone: "+30 22840 52785",
    rating: 4.6,
    review_count: 480,
  },
  {
    id: "fyssilanis",
    name: "Fisilanis (Fyssilanis)",
    area: "Logaras",
    island: "Paros",
    category: "restaurant",
    cuisine: "Poisson · taverne familiale 1964",
    highlight: true,
    coords: [37.0518, 25.2618],
    notes: [
      { author: "Liste 1", text: "Restos locaux grecs ⭐ (peu de Français)." },
      { author: "Liste 4", text: "Spécialiste du poisson — coup de cœur, excellente qualité des produits de la mer." },
    ],
    instagram: "fisilanis_hotel_restaurant",
    instagram_url: "https://www.instagram.com/fisilanis_hotel_restaurant/",
    phone: "+30 22840 41530",
    google_maps_url: "https://maps.app.goo.gl/RGorWnbop74YPdRk6",
    rating: 4.5,
    review_count: 460,
  },
  {
    id: "taverna-julia",
    name: "Taverna Julia",
    area: "Drios",
    island: "Paros",
    category: "restaurant",
    cuisine: "Grec traditionnel, vue mer",
    highlight: true,
    coords: [37.0349, 25.2626],
    notes: [
      { author: "Liste 1", text: "⭐ Pour moi le meilleur spot, de ouf, hyper belle vue." },
    ],
    phone: "+30 22840 41036",
    rating: 4.5,
    review_count: 89,
  },
  {
    id: "yemeni",
    name: "Yemeni Wine Restaurant",
    area: "Vieille ville · Naoussa",
    island: "Paros",
    category: "restaurant",
    cuisine: "Grec moderne · carte des vins",
    reservation: true,
    coords: [37.1248, 25.2400],
    notes: [
      { author: "Liste 2", text: "Très bon, très sympa, il faut réserver." },
      { author: "Liste 3", text: "Yemeni — recommandé." },
    ],
    instagram: "yemeni.paros",
    instagram_url: "https://www.instagram.com/yemeni.paros/",
    website: "https://www.yemeni.gr/",
    phone: "+30 22840 51445",
    rating: 4.5,
    review_count: 950,
  },
  {
    id: "kima",
    name: "Kima Restaurant Paros",
    area: "Drios",
    island: "Paros",
    category: "restaurant",
    cuisine: "Poisson · bord de mer",
    coords: [37.0353, 25.2638],
    notes: [
      { author: "Liste 3", text: "Kima restaurant — restaurant du port (table blanche)." },
      { author: "Liste 4", text: "Taverne de poissons en bord de mer, ambiance détendue, fruits de mer frais et copieux." },
    ],
    instagram: "kimarestaurant",
    instagram_url: "https://www.instagram.com/kimarestaurant/",
    website: "https://kimarestaurant.com",
    phone: "+30 22840 41180",
    google_maps_url: "https://maps.app.goo.gl/DRPBxA42ADLaNfZv5",
    rating: 4.7,
    review_count: 380,
  },
  {
    id: "sousouro",
    name: "Sousouro",
    area: "Vieille ville · Naoussa",
    island: "Paros",
    category: "bar",
    cuisine: "Café · cocktails · bowls",
    coords: [37.1249, 25.2398],
    notes: [
      { author: "Liste 3", text: "Sousouro." },
    ],
    instagram: "sousouro_",
    instagram_url: "https://www.instagram.com/sousouro_/",
    phone: "+30 22840 53113",
    rating: 4.5,
    review_count: 69,
  },
  {
    id: "katsounas",
    name: "Tavern Katsounas",
    area: "Santa Maria · Naoussa",
    island: "Paros",
    category: "restaurant",
    cuisine: "Poisson · brochettes",
    highlight: true,
    reservation: true,
    coords: [37.1295, 25.2660],
    notes: [
      { author: "Liste 2", text: "Resto brochettes Kolimbithres — taverne en hauteur, la première en venant de Naoussa." },
      { author: "Liste 3", text: "Katsounas ⛔ — le meilleur." },
    ],
    phone: "+30 22840 51246",
    rating: 4.3,
    review_count: 291,
  },
  {
    id: "glafkos",
    name: "Taverna Glafkos",
    area: "Agios Dimitrios · Naoussa",
    island: "Paros",
    category: "restaurant",
    cuisine: "Poisson · seafood saganaki",
    reservation: true,
    coords: [37.1255, 25.2418],
    notes: [
      { author: "Liste 2", text: "Resto Naoussa Glafkos — il faut réserver." },
    ],
    instagram: "glafkos_taverna",
    instagram_url: "https://www.instagram.com/glafkos_taverna/",
    phone: "+30 22840 52100",
    rating: 4.3,
    review_count: 1500,
  },
  {
    id: "thalami",
    name: "Thalami (To Thalami)",
    area: "Ambelas",
    island: "Paros",
    category: "restaurant",
    cuisine: "Taverne poisson · déjeuner",
    coords: [37.1193, 25.2716],
    notes: [
      { author: "Liste 2", text: "Taverne à Ambelas, super joli cadre, bon plutôt pour le déj. Pas de résa — ne pas prendre la moussaka." },
    ],
    phone: "+30 22840 53351",
    rating: 4.0,
    review_count: 341,
    photo_url: "https://commons.wikimedia.org/wiki/Special:FilePath/Prawns_at_Thalami,_Ambelas.JPG",
  },
  {
    id: "magaia",
    name: "Magaia",
    area: "Parasporos",
    island: "Paros",
    category: "restaurant",
    avoid: true,
    coords: [37.0691, 25.1481],
    notes: [
      { author: "Liste 2", text: "Magaia à Parasporos — pas bon." },
    ],
  },
  {
    id: "taverna-livadaki",
    name: "Livadaki Taverna",
    area: "Plage d'Agia Irini",
    island: "Paros",
    category: "restaurant",
    cuisine: "Taverne de plage · poulpe grillé",
    coords: [37.0524, 25.1397],
    notes: [
      { author: "Liste 2", text: "Très joli spot et authentique, jolie plage." },
    ],
    phone: "+30 694 667 3645",
    rating: 2.2,
    review_count: 97,
  },
  {
    id: "byzantino",
    name: "Byzantino",
    area: "Prodromos",
    island: "Paros",
    category: "restaurant",
    cuisine: "Grec traditionnel familial",
    coords: [37.0612, 25.2392],
    notes: [
      { author: "Liste 4", text: "Ambiance grecque traditionnelle, excellente cuisine méditerranéenne (poissons, viandes, mezzés), service chaleureux." },
    ],
    phone: "+30 2284 045273",
    google_maps_url: "https://maps.app.goo.gl/nfzmSva7UutEAz6c6",
    rating: 4.4,
    review_count: 84,
  },
  {
    id: "kallitechniko",
    name: "Kallitechniko Kafenio",
    area: "Prodromos",
    island: "Paros",
    category: "restaurant",
    cuisine: "Mezedopoleio · café-resto arty",
    coords: [37.0610, 25.2395],
    notes: [
      { author: "Liste 4", text: "Petit café-restaurant arty dans les ruelles, cafés, vins, mezés faits maison, ambiance créative." },
    ],
    phone: "+30 22840 42033",
    google_maps_url: "https://maps.app.goo.gl/sY4fuQxg6Em3Ux7B7",
    rating: 4.3,
    review_count: 93,
  },
  {
    id: "santa-pacou",
    name: "Santa Pacou",
    area: "Kostos",
    island: "Paros",
    category: "restaurant",
    cuisine: "Vue spectaculaire · revithada poulpe",
    coords: [37.0865, 25.2071],
    notes: [
      { author: "Liste 4", text: "Charmant restaurant en montagne, bon choix de viande et spécialités grecques, vue spectaculaire." },
    ],
    instagram: "santapacou",
    instagram_url: "https://www.instagram.com/santapacou/",
    phone: "+30 697 242 4104",
    google_maps_url: "https://maps.app.goo.gl/mN4ZHdiwGKSw2Kqo8",
    rating: 4.6,
    review_count: 33,
  },
  {
    id: "aliki-resto",
    name: "Aliki Restaurant",
    area: "Port d'Aliki",
    island: "Paros",
    category: "restaurant",
    cuisine: "Grec · poisson frais · familial 1974",
    coords: [36.9870, 25.1689],
    notes: [
      { author: "Liste 3", text: "Aliki resto moypatio." },
      { author: "Liste 4", text: "Établissement familial en bord de mer depuis 1974, cuisine grecque, produits frais, poissons grillés." },
    ],
    instagram: "aliki_restaurant_paros",
    instagram_url: "https://www.instagram.com/aliki_restaurant_paros/",
    website: "https://www.alikirestaurant.com/",
    phone: "+30 2284 091228",
    google_maps_url: "https://maps.app.goo.gl/BsV718AFMtasYkK49",
    rating: 4.4,
    review_count: 320,
  },
  {
    id: "ouzeri-halaris",
    name: "Ouzeri Halaris",
    area: "Port de Piso Livadi",
    island: "Paros",
    category: "restaurant",
    cuisine: "Mezés fruits de mer (poulpe, calamars)",
    coords: [37.0481, 25.2602],
    notes: [
      { author: "Liste 2", text: "Plages : Halaris (en réalité l'ouzeri du port — pas une plage)." },
      { author: "Liste 4", text: "Ouzeri réputé pour ses mezés de fruits de mer (poulpe, crevettes, calamars), ambiance familiale en bord de mer." },
    ],
    phone: "+30 2284 043257",
    google_maps_url: "https://maps.app.goo.gl/2M3Eu94wtXTNoKrFA",
    rating: 4.4,
    review_count: 878,
  },
  {
    id: "mare-nostrum",
    name: "Mare Nostrum",
    area: "Vieux port · Naoussa",
    island: "Paros",
    category: "restaurant",
    cuisine: "Méditerranéen, fruits de mer · vue port",
    coords: [37.1265, 25.2399],
    notes: [
      { author: "Liste 4", text: "Cuisine méditerranéenne et fruits de mer, vue sur le port, idéal pour une soirée tranquille." },
    ],
    instagram: "marenostrumrestaurant",
    instagram_url: "https://www.instagram.com/marenostrumrestaurant/",
    phone: "+30 22840 51225",
    google_maps_url: "https://maps.app.goo.gl/Q3BvsbdYqE4t1Drg8",
    rating: 3.7,
    review_count: 418,
  },
  {
    id: "almond-coffee",
    name: "Almond (Living Well Place)",
    area: "Place principale · Naoussa",
    island: "Paros",
    category: "breakfast",
    cuisine: "Brunch · pancakes · bowls",
    coords: [37.1244, 25.2387],
    notes: [
      { author: "Liste 3", text: "Pour le matin." },
    ],
    instagram: "almond_paros",
    instagram_url: "https://www.instagram.com/almond_paros/",
    website: "https://www.almondlivingwell.com/en/",
    rating: 4.8,
    review_count: 120,
  },
  {
    id: "taverne-laris",
    name: "Taverna Laris",
    area: "Camping Agia Irini",
    island: "Paros",
    category: "restaurant",
    cuisine: "Taverne de plage",
    coords: [37.0520, 25.1395],
    notes: [
      { author: "Liste 2", text: "Dans les meilleures (Blue Oyster, Ministiri, Taverne Laris)." },
    ],
    phone: "+30 22840 91496",
    rating: 3.6,
    review_count: 146,
  },
  {
    id: "monastiri",
    name: "Monastiri (« Ministiri »)",
    area: "Paros Park · Ai Yiannis Detis",
    island: "Paros",
    category: "restaurant",
    cuisine: "Beach club · méditerranéen",
    coords: [37.1554, 25.2228],
    notes: [
      { author: "Liste 2", text: "Dans les meilleures (Blue Oyster, Ministiri, Taverne Laris) — orthographe corrigée : Monastiri." },
    ],
    instagram: "monastiri.paros",
    instagram_url: "https://www.instagram.com/monastiri.paros/",
    website: "https://www.monastiri-paros.gr/",
    phone: "+30 22840 53560",
    rating: 3.5,
    review_count: 180,
  },
  {
    id: "markakis",
    name: "Markakis (taverne, pas plage)",
    area: "Drios",
    island: "Paros",
    category: "restaurant",
    cuisine: "Taverne familiale bord de mer",
    coords: [37.00224, 25.22682],
    notes: [
      { author: "Liste 2", text: "Markakis (en réalité une taverne à Drios, pas une plage)." },
    ],
    rating: 4.4,
    review_count: 350,
  },

  /* ============================== PAROS — PLAGES ============================== */
  {
    id: "kolimbithres",
    name: "Plage de Kolimbithres",
    area: "Baie de Naoussa",
    island: "Paros",
    category: "beach",
    coords: [37.12947, 25.21443],
    notes: [
      { author: "Liste 2", text: "Ski nautique à Kolimbithres." },
    ],
    rating: 4.0,
    review_count: 1378,
  },
  {
    id: "punda",
    name: "Punda Beach Club",
    area: "Marpissa · côte est",
    island: "Paros",
    category: "beach",
    coords: [37.02811, 25.25216],
    notes: [
      { author: "Liste 3", text: "Punda." },
    ],
    instagram: "pundacoast",
    instagram_url: "https://www.instagram.com/pundacoast/",
    website: "https://pundacoast.com/",
    rating: 3.5,
    review_count: 95,
  },
  {
    id: "parasporos",
    name: "Parasporos",
    area: "Sud de Parikia",
    island: "Paros",
    category: "beach",
    coords: [37.07181, 25.12745],
    notes: [
      { author: "Liste 3", text: "Paras poros." },
      { author: "Liste 5", text: "Personne, plage non aménagée, mer hyper belle, vous allez être seul seul." },
    ],
    rating: 4.5,
    review_count: 65,
  },
  {
    id: "palm-beach",
    name: "Palm Beach",
    area: "Agia Eirini · côte ouest",
    island: "Paros",
    category: "beach",
    coords: [37.05497, 25.10994],
    notes: [
      { author: "Liste 3", text: "Palm beach." },
    ],
    instagram: "palmbeachparos",
    instagram_url: "https://www.instagram.com/palmbeachparos/",
    rating: 4.0,
    review_count: 80,
  },
  {
    id: "golden-beach",
    name: "Golden Beach (Chrissi Akti)",
    area: "Côte sud-est",
    island: "Paros",
    category: "beach",
    coords: [37.01054, 25.24038],
    notes: [
      { author: "Liste 3", text: "Golden beach (blue lagon)." },
    ],
    rating: 4.5,
    review_count: 414,
  },
  {
    id: "faragas",
    name: "Plage Faragas",
    area: "Sud (près d'Aliki)",
    island: "Paros",
    category: "beach",
    coords: [36.98641, 25.15558],
    notes: [
      { author: "Liste 3", text: "Plage Faragas." },
      { author: "Liste 5", text: "Plage Farangas." },
    ],
    instagram: "faragas_beach",
    instagram_url: "https://www.instagram.com/faragas_beach/",
    website: "https://www.faragas-beach.gr/",
    rating: 4.5,
    review_count: 120,
    photo_url: "https://upload.wikimedia.org/wikipedia/commons/e/e5/Cyclades_Paros_Faragas_Beach_-_panoramio.jpg",
  },
  {
    id: "aliki-beach",
    name: "Plage d'Aliki",
    area: "Sud · village d'Aliki",
    island: "Paros",
    category: "beach",
    coords: [36.99248, 25.1374],
    notes: [
      { author: "Liste 3", text: "Aliki." },
    ],
    rating: 4.5,
    review_count: 368,
  },
  {
    id: "katsouna-beach",
    name: "Plage Katsouna (Santa Maria)",
    area: "Santa Maria · Naoussa",
    island: "Paros",
    category: "beach",
    coords: [37.13167, 25.27711],
    notes: [
      { author: "Liste 2", text: "Katsouna — derrière la taverne Katsounas à Santa Maria." },
    ],
    rating: 4.0,
    review_count: 991,
  },
  {
    id: "livadaki",
    name: "Plage Livadaki / Agia Irini",
    area: "Côte ouest",
    island: "Paros",
    category: "beach",
    coords: [37.0467, 25.108],
    notes: [
      { author: "Liste 2", text: "Plage Livadaki." },
    ],
    rating: 4.5,
    review_count: 39,
  },
  {
    id: "pomodros",
    name: "Pounta (« Pomodros »)",
    area: "Port de ferry vers Antiparos",
    island: "Paros",
    category: "beach",
    coords: [37.03041, 25.09778],
    notes: [
      { author: "Liste 2", text: "Pomodros (probablement Pounta, port du ferry pour Antiparos)." },
    ],
  },
  {
    id: "beach-project",
    name: "Beach Project",
    area: "Naoussa",
    island: "Paros",
    category: "beach",
    coords: [37.1232, 25.2495],
    notes: [
      { author: "Liste 3", text: "Beach project." },
    ],
    rating: 4.1,
    review_count: 54,
  },

  /* ============================== ANTIPAROS ============================== */
  {
    id: "sunset-deseo",
    name: "Sunset Deseo / Sunset Antiparos",
    area: "Plage Sifneiko · Antiparos",
    island: "Antiparos",
    category: "bar",
    cuisine: "Bar coucher de soleil · resto",
    highlight: true,
    coords: [37.04128, 25.07566],
    notes: [
      { author: "Liste 1", text: "⭐ Boire un verre au sunset Deseo." },
      { author: "Liste 2", text: "Antiparos coucher de soleil sunset." },
      { author: "Liste 3", text: "Sunset Deseo Antiparos." },
    ],
    instagram: "sunsetantiparos",
    instagram_url: "https://www.instagram.com/sunsetantiparos/",
    website: "https://sunsetantiparos.com/",
    rating: 4.0,
    review_count: 83,
  },
  {
    id: "rooster",
    name: "The Rooster Antiparos",
    area: "Baie de Livadia · Antiparos",
    island: "Antiparos",
    category: "hotel",
    cuisine: "Hôtel boutique wellness · bar",
    highlight: true,
    coords: [37.01874, 25.0479],
    notes: [
      { author: "Liste 1", text: "⭐ Hôtel pour prendre un verre, très beau." },
    ],
    instagram: "therooster.antiparos",
    instagram_url: "https://www.instagram.com/therooster.antiparos/",
    website: "https://theroosterantiparos.com/",
    rating: 4.0,
    review_count: 26,
  },
  {
    id: "kalokeri",
    name: "Kalokeri",
    area: "Chora · Antiparos",
    island: "Antiparos",
    category: "restaurant",
    cuisine: "Grec (dîner)",
    coords: [37.04046, 25.07914],
    notes: [
      { author: "Liste 2", text: "Dîner Kalokeri (resto pas très joli mais très bon)." },
    ],
    instagram: "kalokerirestaurant",
    instagram_url: "https://www.instagram.com/kalokerirestaurant/",
    rating: 4.6,
    review_count: 339,
  },
  {
    id: "lolos",
    name: "Lollo's Pizzeria",
    area: "Chora / Port · Antiparos",
    island: "Antiparos",
    category: "restaurant",
    cuisine: "Pizza / pâtes au feu de bois",
    coords: [37.04046, 25.07914],
    notes: [
      { author: "Liste 3", text: "Lolo's Antiparos." },
      { author: "Liste 5", text: "Pizza pâtes de rêve." },
    ],
    instagram: "lollosantiparos",
    instagram_url: "https://www.instagram.com/lollosantiparos/",
    rating: 4.0,
    review_count: 387,
  },
  {
    id: "soros-beach",
    name: "Plage de Soros",
    area: "Sud d'Antiparos",
    island: "Antiparos",
    category: "beach",
    coords: [36.97194, 25.05917],
    notes: [
      { author: "Liste 2", text: "Antiparos déjeuner et plage Soros top et très bon." },
      { author: "Liste 3", text: "Journée à Antiparos (Soros)." },
    ],
    rating: 4.5,
    review_count: 238,
  },
  {
    id: "soros-beach-club",
    name: "Soros Beach Antiparos (club)",
    area: "Plage Soros · Antiparos",
    island: "Antiparos",
    category: "beach",
    cuisine: "Hôtel · resto · beach club",
    coords: [36.97194, 25.05917],
    notes: [
      { author: "Liste 5", text: "Soros Beach Club." },
    ],
    instagram: "sorosbeachantiparos",
    instagram_url: "https://www.instagram.com/sorosbeachantiparos/",
    website: "https://www.sorosbeach.gr/",
    rating: 3.0,
    review_count: 372,
  },
  {
    id: "fanari-beach",
    name: "Fanari Beach",
    area: "Près du port · Antiparos",
    island: "Antiparos",
    category: "beach",
    coords: [37.0343, 25.08143],
    notes: [
      { author: "Liste 1", text: "Plage Fanari." },
      { author: "Liste 5", text: "Fanari Beach." },
    ],
    website: "https://fanaribeach.gr/",
    rating: 4.5,
    review_count: 40,
  },
  {
    id: "beach-house",
    name: "The Beach House",
    area: "Apantima · Antiparos",
    island: "Antiparos",
    category: "hotel",
    cuisine: "Auberge + resto bord de mer",
    coords: [36.9905, 25.0608],
    notes: [
      { author: "Liste 5", text: "Beach House." },
    ],
    instagram: "beachhouseantiparos",
    instagram_url: "https://www.instagram.com/beachhouseantiparos/",
    website: "https://beachhouseantiparos.com/",
    rating: 3.6,
    review_count: 298,
  },
  {
    id: "captain-pepinos",
    name: "Captain Pipinos",
    area: "Agios Georgios · Antiparos",
    island: "Antiparos",
    category: "restaurant",
    cuisine: "Poisson · vue sur Despotiko",
    coords: [36.97433, 25.0281],
    notes: [
      { author: "Liste 5", text: "Resto grec et plus beau coucher de soleil de l'île (orthographe corrigée : Pipinos)." },
    ],
    instagram: "captain_pipinos",
    instagram_url: "https://www.instagram.com/captain_pipinos/",
    website: "https://captainpipinos.com/",
    rating: 3.9,
    review_count: 1130,
  },

  /* ============================== PAROS — ACTIVITÉS ============================== */
  {
    id: "boat-day",
    name: "Journée bateau (Paros)",
    area: "Naoussa · départ",
    island: "Paros",
    category: "activity",
    coords: [37.1262, 25.2402],
    notes: [
      { author: "Liste 3", text: "Journée bateau." },
    ],
  },
  {
    id: "waterski-kolimbithres",
    name: "WaterSkiZone Kolimbithres",
    area: "Kolimbithres · Naoussa",
    island: "Paros",
    category: "activity",
    cuisine: "Ski nautique · wakeboard",
    coords: [37.12947, 25.21443],
    notes: [
      { author: "Liste 2", text: "Ski nautique à Kolimbithres." },
    ],
    website: "https://www.waterskizone.com/",
    phone: "+30 6944 242227",
    rating: 4.5,
    review_count: 19,
  },

  /* ============================== ATHÈNES ============================== */
  {
    id: "cinapos",
    name: "Cinapos",
    area: "Thiseio · Irakleidon 10",
    island: "Athènes",
    category: "restaurant",
    coords: [37.9766, 23.7195],
    notes: [
      { author: "Programme", text: "On a kiffé !" },
    ],
    instagram: "cinapos",
    instagram_url: "https://www.instagram.com/cinapos/",
    website: "https://cinapos.com",
    rating: 4.3,
    review_count: 65,
  },
  {
    id: "voylkanizater",
    name: "Voulkanizater",
    area: "Koukaki",
    island: "Athènes",
    category: "restaurant",
    coords: [37.9657, 23.7253],
    notes: [
      { author: "Programme", text: "Recommandé (on m'a conseillé)." },
    ],
    instagram: "voulkanizater.ath",
    instagram_url: "https://www.instagram.com/voulkanizater.ath/",
    website: "https://voulkanizater.com",
  },
  {
    id: "manari",
    name: "Manari Taverna",
    area: "Plateia Agion Theodoron",
    island: "Athènes",
    category: "restaurant",
    coords: [37.9802, 23.7290],
    notes: [
      { author: "Programme", text: "Recommandé." },
    ],
    instagram: "manaritaverna",
    instagram_url: "https://www.instagram.com/manaritaverna/",
    website: "https://www.manaritaverna.com",
    rating: 4.4,
    review_count: 1419,
  },
  {
    id: "isandsia",
    name: "Isandsia",
    area: "Monastiraki · Melanthiou 2",
    island: "Athènes",
    category: "restaurant",
    coords: [37.9778, 23.7256],
    notes: [
      { author: "Programme", text: "Recommandé (orthographe à confirmer)." },
    ],
    rating: 4.1,
    review_count: 9,
  },
  {
    id: "regal-hotel",
    name: "Regal Hotel Mitropoleos",
    area: "Près de Syntagma",
    island: "Athènes",
    category: "hotel",
    coords: [37.9762, 23.7282],
    notes: [
      { author: "Programme", text: "Check-in Athènes." },
    ],
    website: "https://www.regalhotels.gr/",
    rating: 4.4,
    review_count: 2421,
  },

  /* ============================== SIFNOS ============================== */
  {
    id: "vahti-beach",
    name: "Plage de Vathi",
    area: "Vathi · sud-ouest",
    island: "Sifnos",
    category: "beach",
    coords: [36.9219, 24.6647],
    notes: [
      { author: "Programme", text: "Sunbeds at Nostos — il faut réserver en ligne." },
    ],
    rating: 4.5,
    review_count: 508,
  },
  {
    id: "nostos-sifnos",
    name: "Nostos Beach Bar",
    area: "Plage de Vathi · Sifnos",
    island: "Sifnos",
    category: "bar",
    reservation: true,
    coords: [36.9220, 24.6650],
    notes: [
      { author: "Programme", text: "Réserver les sunbeds en ligne." },
    ],
    website: "https://nostosbeachbar.gr/en/",
    rating: 4.4,
    review_count: 473,
  },
  {
    id: "tsika",
    name: "Tsikali Taverna",
    area: "Vathi",
    island: "Sifnos",
    category: "restaurant",
    coords: [36.9216, 24.6644],
    notes: [
      { author: "Programme", text: "Lunch at Tsika / Manolis." },
    ],
    website: "https://tsikali.com",
    rating: 4.1,
    review_count: 535,
  },
  {
    id: "manolis",
    name: "Manolis Taverna",
    area: "Plage de Vathi",
    island: "Sifnos",
    category: "restaurant",
    coords: [36.9221, 24.6651],
    notes: [
      { author: "Programme", text: "Lunch at Tsika / Manolis." },
    ],
    website: "https://www.manolistaverna.gr/",
    rating: 4.2,
    review_count: 385,
  },
  {
    id: "loggia",
    name: "Loggia Wine Bar",
    area: "Kastro · falaise",
    island: "Sifnos",
    category: "bar",
    reservation: true,
    coords: [36.9836, 24.7556],
    notes: [
      { author: "Programme", text: "Sunset + dîner. Descendre au sunset voir l'église des Sept Martyrs, c'est sublime !!" },
    ],
    rating: 4.3,
    review_count: 335,
  },
  {
    id: "kafeneio-drakaki",
    name: "Kafeneio Drakakis",
    area: "Apollonia · ruelle piétonne",
    island: "Sifnos",
    category: "bar",
    coords: [36.9778, 24.7311],
    notes: [
      { author: "Programme", text: "No reservation — dîner en centre ville top." },
    ],
    instagram: "kafeneiodrakakis",
    instagram_url: "https://www.instagram.com/kafeneiodrakakis/",
    rating: 4.3,
    review_count: 2455,
  },
  {
    id: "paralia-beach-bar",
    name: "Paralia Beach Bar",
    area: "Kamares",
    island: "Sifnos",
    category: "bar",
    coords: [36.9889, 24.6747],
    notes: [
      { author: "Programme", text: "Collé à l'hôtel, hyper sympa." },
    ],
    instagram: "paraliasifnos",
    instagram_url: "https://www.instagram.com/paraliasifnos/",
    website: "https://paraliabeachbarsifnos.gr/",
    rating: 4.3,
    review_count: 50,
  },
  {
    id: "yalos-beach",
    name: "Yalos Seaside Obsession",
    area: "Platis Gialos",
    island: "Sifnos",
    category: "restaurant",
    coords: [36.9181, 24.7286],
    notes: [
      { author: "Programme", text: "On a pris des poufs, c'était un kiffe." },
    ],
    instagram: "yalos_sifnos",
    instagram_url: "https://www.instagram.com/yalos_sifnos/",
    rating: 4.6,
    review_count: 461,
  },
  {
    id: "pelicanos",
    name: "Pelicanos",
    area: "Faros",
    island: "Sifnos",
    category: "restaurant",
    coords: [36.9302, 24.7400],
    notes: [
      { author: "Programme", text: "Lunch (14h)." },
    ],
    website: "https://pelicanossifnos.gr/",
    rating: 3.7,
    review_count: 31,
  },
  {
    id: "bostani",
    name: "Bostani Bar & Restaurant",
    area: "Poulati · Verina Astra hotel",
    island: "Sifnos",
    category: "restaurant",
    coords: [36.9870, 24.7440],
    notes: [
      { author: "Programme", text: "Sublime l'endroit à l'heure du sunset, mais pas la meilleure bouffe." },
    ],
    instagram: "bostanisifnos",
    instagram_url: "https://www.instagram.com/bostanisifnos/",
    website: "https://verinahotelsifnos.com/bostani-bar-restaurant/",
    rating: 4.5,
    review_count: 49,
  },
  {
    id: "vroulidia",
    name: "Paralia Vroulidia",
    area: "Nord-ouest · Sifnos",
    island: "Sifnos",
    category: "beach",
    reservation: true,
    coords: [37.0250, 24.6889],
    notes: [
      { author: "Programme", text: "Transats à réserver en avance. On a passé la journée." },
    ],
    rating: 4.3,
    review_count: 125,
  },
  {
    id: "cheronissos-beach",
    name: "Cheronissos Beach",
    area: "Pointe nord · Sifnos",
    island: "Sifnos",
    category: "beach",
    coords: [37.0317, 24.7050],
    notes: [
      { author: "Programme", text: "Pas fait." },
    ],
    rating: 4.3,
    review_count: 150,
    photo_url: "https://commons.wikimedia.org/wiki/Special:FilePath/Cyclades_Sifnos_Keronisos_Port_-_panoramio.jpg",
  },
  {
    id: "captain-george",
    name: "Captain George",
    area: "Kastro Seralia",
    island: "Sifnos",
    category: "restaurant",
    coords: [36.9831, 24.7570],
    notes: [
      { author: "Programme", text: "Pas fait, il paraît top." },
    ],
    instagram: "captaingeorgesifnos",
    instagram_url: "https://www.instagram.com/captaingeorgesifnos/",
    rating: 4.1,
    review_count: 59,
  },
  {
    id: "perivoli",
    name: "Perivoli Restaurant",
    area: "Artemonas",
    island: "Sifnos",
    category: "restaurant",
    coords: [36.9824, 24.7305],
    notes: [
      { author: "Programme", text: "Dîner 22h." },
    ],
    instagram: "perivoli_restaurant_sifnos",
    instagram_url: "https://www.instagram.com/perivoli_restaurant_sifnos/",
    rating: 4.5,
    review_count: 283,
  },

  /* ============================== MILOS ============================== */
  {
    id: "tsigrado",
    name: "Tsigrado Beach",
    area: "Côte sud · Milos",
    island: "Milos",
    category: "beach",
    coords: [36.6730, 24.4520],
    notes: [
      { author: "Programme", text: "Petite plage où tu descends par une échelle." },
    ],
    rating: 4.5,
    review_count: 600,
    photo_url: "https://commons.wikimedia.org/wiki/Special:FilePath/Tsigrado_Beach_on_Milos_Island%2C_Greece.jpg",
  },
  {
    id: "firiplaka",
    name: "Firiplaka Beach",
    area: "Côte sud · Milos",
    island: "Milos",
    category: "beach",
    coords: [36.6720, 24.4625],
    notes: [
      { author: "Programme", text: "Trop trop beau." },
    ],
    rating: 4.5,
    review_count: 620,
    photo_url: "https://commons.wikimedia.org/wiki/Special:FilePath/Paralia_Firiplaka_on_Milos_Island%2C_Greece_as_seen_from_the_north.jpg",
  },
  {
    id: "sirocco",
    name: "Sirocco Volcanic Restaurant",
    area: "Plage Paleochori",
    island: "Milos",
    category: "restaurant",
    coords: [36.6800, 24.5097],
    notes: [
      { author: "Programme", text: "Lunch 15h. Aller sur la plage toute à gauche du resto, c'est sublime et tu es seul au monde." },
    ],
    website: "https://siroccomilos.gr/",
    rating: 3.6,
    review_count: 866,
  },
  {
    id: "mosaic-milos",
    name: "Mosaic Milos",
    area: "Plaka",
    island: "Milos",
    category: "bar",
    coords: [36.7378, 24.4222],
    notes: [
      { author: "Programme", text: "Sunset — on a pas fait mais canon." },
    ],
    instagram: "mosaic.milos",
    instagram_url: "https://www.instagram.com/mosaic.milos/",
    website: "https://mosaicmilos.gr/",
    rating: 4.4,
    review_count: 40,
  },
  {
    id: "okto",
    name: "Restaurant Okto",
    area: "Trypiti",
    island: "Milos",
    category: "restaurant",
    coords: [36.7280, 24.4214],
    notes: [
      { author: "Programme", text: "Dinner — Okto ou Barriello." },
    ],
    instagram: "okto.milos",
    instagram_url: "https://www.instagram.com/okto.milos/",
    website: "https://www.restaurant-okto.gr/",
    rating: 4.5,
    review_count: 356,
  },
  {
    id: "barriello",
    name: "Barriello",
    area: "Trypiti",
    island: "Milos",
    category: "restaurant",
    coords: [36.7270, 24.4220],
    notes: [
      { author: "Programme", text: "Dinner — Okto ou Barriello." },
    ],
    website: "https://www.barriello.com/",
    rating: 4.6,
    review_count: 1244,
  },
  {
    id: "mandrakia",
    name: "Mandrakia Village",
    area: "Côte nord · Milos",
    island: "Milos",
    category: "beach",
    coords: [36.7475, 24.4658],
    notes: [
      { author: "Programme", text: "Village de pêcheurs." },
    ],
    rating: 4.5,
    review_count: 200,
    photo_url: "https://commons.wikimedia.org/wiki/Special:FilePath/Cyclades_Milos_Mandrakia_13092014_-_panoramio.jpg",
  },
  {
    id: "medusa",
    name: "Medusa Restaurant",
    area: "Mandrakia",
    island: "Milos",
    category: "restaurant",
    reservation: true,
    coords: [36.7475, 24.4660],
    notes: [
      { author: "Programme", text: "No reservation — donner son nom et attendre sur la plage." },
    ],
    website: "https://medusamilos.gr/",
    rating: 4.4,
    review_count: 2451,
  },
  {
    id: "sarakiniko",
    name: "Sarakiniko Beach",
    area: "Côte nord · Milos",
    island: "Milos",
    category: "beach",
    coords: [36.74282, 24.45833],
    notes: [
      { author: "Programme", text: "Sarakiniko Beach." },
    ],
    rating: 4.7,
    review_count: 2416,
    photo_url: "https://commons.wikimedia.org/wiki/Special:FilePath/Sarakiniko_Beach_on_Milos_Island%2C_Greece_with_a_view_of_the_Aegean_Sea.jpg",
  },
  {
    id: "klima",
    name: "Klima",
    area: "Côte ouest · Milos",
    island: "Milos",
    category: "beach",
    coords: [36.7194, 24.4150],
    notes: [
      { author: "Programme", text: "Klima for Sunset." },
    ],
    rating: 4.6,
    review_count: 300,
    photo_url: "https://commons.wikimedia.org/wiki/Special:FilePath/Cyclades_Milos_Klima_Eglise_-_panoramio.jpg",
  },
  {
    id: "astakas",
    name: "Astakas Milos",
    area: "Klima",
    island: "Milos",
    category: "restaurant",
    reservation: true,
    coords: [36.7197, 24.4148],
    notes: [
      { author: "Programme", text: "6 personnes, 20h30." },
    ],
    website: "https://astakasmilos.gr/",
    rating: 4.2,
    review_count: 797,
  },
  {
    id: "domes-white-coves",
    name: "Domes White Coast / Makris",
    area: "Milos",
    island: "Milos",
    category: "hotel",
    reservation: true,
    coords: [36.7300, 24.5550],
    notes: [
      { author: "Programme", text: "Dîner au Makris Restaurant, 20h30." },
    ],
    website: "https://domesresorts.com/domeswhitecoastmilos/",
    rating: 4.0,
    review_count: 308,
  },
  {
    id: "calypso-boat",
    name: "Calypso Boat (journée bateau)",
    area: "Port d'Adamas · Milos",
    island: "Milos",
    category: "activity",
    coords: [36.7228, 24.4380],
    notes: [
      { author: "Programme", text: "Boat day Calypso." },
    ],
    website: "https://milosboatrental.com/",
    rating: 5.0,
    review_count: 19,
  },

  /* ============================== KIMOLOS ============================== */
  {
    id: "goupa-kara",
    name: "Goupa Kara",
    area: "Près de Psathi · Kimolos",
    island: "Kimolos",
    category: "beach",
    coords: [36.7975, 24.5728],
    notes: [
      { author: "Programme", text: "Goupa Kara." },
    ],
    rating: 4.6,
    review_count: 39,
  },
  {
    id: "rema",
    name: "Rema Beach",
    area: "Près Goupa · Kimolos",
    island: "Kimolos",
    category: "beach",
    coords: [36.7960, 24.5760],
    notes: [
      { author: "Programme", text: "Rema Beach." },
    ],
    rating: 4.5,
    review_count: 20,
  },
  {
    id: "prassa",
    name: "Prassa Beach",
    area: "Pointe NE · Kimolos",
    island: "Kimolos",
    category: "beach",
    coords: [36.8330, 24.6033],
    notes: [
      { author: "Programme", text: "Prassa Beach." },
    ],
    rating: 4.8,
    review_count: 497,
  },
  {
    id: "prasonisi-kimolos",
    name: "Prasonisi",
    area: "Près de Prassa · Kimolos",
    island: "Kimolos",
    category: "restaurant",
    coords: [36.8325, 24.6028],
    notes: [
      { author: "Programme", text: "Déj : Prasonisi / The Wave / To Kyma." },
    ],
    rating: 4.6,
    review_count: 224,
  },
  {
    id: "to-kyma-kimolos",
    name: "To Kyma / The Wave",
    area: "Port de Psathi · Kimolos",
    island: "Kimolos",
    category: "restaurant",
    coords: [36.7967, 24.5772],
    notes: [
      { author: "Programme", text: "Déj : Prasonisi / The Wave / To Kyma (« To Kyma » = « The Wave », même resto)." },
    ],
    website: "https://kyma-kimolos.gr/",
    rating: 4.0,
    review_count: 339,
  },
];
